### ISSUE TITLE
Typo in SMART visible issues error when viewing paste, as well as reallocated sectors not displaying, unsure if that was intentional design.

### ISSUE THREAD

**Issue by zleyyij** [PipeItToDevNull/Get-Specs#16]
https://paste.rtech.support/selif/i3fdkbdo.html
![image](https://user-images.githubusercontent.com/75810274/146304684-f9224b0e-0ab3-47d1-ac66-f74a5e318897.png)

**Comment by PipeItToDevNull** [comment]
[i3fdkbdo.txt](https://github.com/PipeItToDevNull/Get-Specs/files/7727072/i3fdkbdo.txt)

HTML uploaded as .txt for historical purposes

**Comment by PipeItToDevNull** [comment]
This issue was resolved 
![image](https://user-images.githubusercontent.com/25917750/146389695-7aa6c323-16a9-4f75-8461-eab7b4feec17.png)
