### ISSUE TITLE
Add detection of Hardware Accelerated GPU Scheduling (HAGS)

### ISSUE THREAD

**Issue by m6qh9mkyn9** [PipeItToDevNull/Get-Specs#59]
Hags is a newer windows feature that comes enabled on some systems by default for some reason. In older games such as the Batman titles, VR Games, and OBS, it causes extreme stuttering/fps loss/ and other issues. At the moment there is less than a 2% difference in like 95% of titles, so it seems to do more harm then help. Currently it is automatically off on a clean windows 10 install, and seemingly random on windows 11 installs. It would be useful to add a check to see if it is enabled.
It seems you can check this with 
reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers" /v HwSchMode
with HwSchMode 2 meaning hags is on, with 1 meaning it is off, but it seems the key is not always present on all systems.

**Comment by PipeItToDevNull** [comment]
```powershell
Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Control\GraphicsDrivers -Name HwSchMode
```

**Comment by PipeItToDevNull** [comment]
https://github.com/PipeItToDevNull/Get-Specs/commit/f5d7394f43a8a52c88d2ddb8fe53fca923516f2f
