### ISSUE TITLE
Hex field for SMART data

### ISSUE THREAD

**Issue by Bjoolz** [PipeItToDevNull/Get-Specs#60]
Some drives store other info in some parameters which is not possible to spot with just decimal. Adding a field for Hex would make this possible to spot.

**Comment by PipeItToDevNull** [comment]
This is an issue in [Get-SMART](https://github.com/PipeItToDevNull/Get-Smart) specifically relating to Issue [2](https://github.com/PipeItToDevNull/Get-Smart/issues/2) [3](https://github.com/PipeItToDevNull/Get-Smart/issues/3)
