### ISSUE TITLE
Add RAM partnumber

### ISSUE THREAD

**Issue by Cpt-Dingus** [PipeItToDevNull/Get-Specs#70]
Command to get it is `wmic memorychip get partnumber`

**Comment by SealsRock12** [comment]
there seem to already be partnumbers:
![image](https://user-images.githubusercontent.com/47796480/167049816-0142a295-ce0c-4183-94f1-4893a8d0f8e5.png)
this matches with the command that you gave:
```
powershell> wmic memorychip get partnumber
PartNumber        
M378A1K43DB2-CTD  
M378A1K43DB2-CTD
```

**Comment by PipeItToDevNull** [comment]
re-open if this is not resolved

**Comment by Cpt-Dingus** [comment]
![image](https://user-images.githubusercontent.com/100243410/167069892-51f15074-4004-479d-ba24-d2461158fda2.png)
 

Two separate runs, no part no#

![image](https://user-images.githubusercontent.com/100243410/167069909-5cab4a76-d05f-419e-b951-3b95c7f84376.png)
To verify the command works, tested it and it does output part number.

**Comment by Cpt-Dingus** [comment]
Updated version of specs works, shows the part number properly.
